AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Go Lambda Function

Resources:
  HelloGoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: function.zip
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
